import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import { useEffect } from 'react'
import { CookiesProvider } from 'react-cookie';

interface Props {
  data: Count
}

type Count = {
  count: number
}

const Home: NextPage<Props> = ({ data }) => {
  return (
    <CookiesProvider>
      <div className={styles.container}>
        {/* HEAD */}
        <Head>
          <title>BSQ Gym Tracker</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* HERO */}
        <Hero gymCount={data.count} />
      </div>
    </CookiesProvider>
  )
}

// Server Side Rendering
export const getServerSideProps: GetServerSideProps = async () => {
  // Request
  const res = await fetch("https://bsqgymdb.herokuapp.com/count")
  const data = await res.json()

  return {
    props: {
      data
    }
  }
}

export default Home
