import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      {/* HEAD */}
      <Head>
        <title>BSQ Gym Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HERO */}
      <Hero title='BSQ Gym Tracker' />

      
    </div>
  )
}

export default Home
