import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import { useEffect } from 'react'

interface Props {
  data: Count
}

type Count = {
  count: number
}

const Home: NextPage<Props> = ({ data }) => {
  return (
    <div className={styles.container}>
      {/* HEAD */}
      <Head>
        <title>BSQ Gym Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HERO */}
      <Hero gymCount={data.count} />
    </div>
  )
}

// Server Side Rendering
export const getServerSideProps: GetServerSideProps = async () => {
  // Request
  const res = await fetch("http://localhost:8080/count")
  const data = await res.json() 

  return {
    props: {
      data
    }
  }
}

export default Home
